# Generated by Django 2.2.10 on 2020-03-17 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_record_id', models.PositiveSmallIntegerField(db_index=True)),
                ('db_key', models.CharField(db_index=True, max_length=32, unique=True)),
                ('db_who_name', models.CharField(max_length=16)),
                ('db_group', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_size', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_alignment', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_move_speed', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_attack_speed', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_heal_speed', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_hide_delay', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_base_health', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_level_health', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_base_mana', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_level_mana', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_base_weapon_use', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_level_weapon_use', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_base_claw_damage', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_level_claw_damage', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_random_claw_damage', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_base_steal', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_level_steal', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_base_move_silent', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_level_move_silent', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_armor', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_spell_armor', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_hear_noise', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_poison_chance', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_shadow_damage_percent', models.SmallIntegerField(blank=0, default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_record_id', models.PositiveSmallIntegerField(db_index=True)),
                ('db_key', models.CharField(db_index=True, max_length=32, unique=True)),
                ('db_mana', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_level_mana', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_caster_desc', models.CharField(max_length=256, null=True)),
                ('db_victim_desc', models.CharField(max_length=256, null=True)),
                ('db_room_desc', models.CharField(max_length=256, null=True)),
                ('db_alignment', models.PositiveSmallIntegerField(blank=66, default=66)),
                ('db_failure_desc', models.CharField(max_length=256, null=True)),
                ('db_min_level', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_class_id', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_group', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_room', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_failure_chance', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_casting_time', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_object_required', models.CharField(max_length=32, null=True)),
                ('db_object_consumed', models.BooleanField(default=False)),
                ('db_silent', models.BooleanField(default=False)),
                ('db_reveals', models.BooleanField(default=False)),
                ('db_memorize', models.BooleanField(default=False)),
                ('db_command', models.CharField(max_length=32, null=True)),
                ('db_command_priv', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpellEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_effect_kind', models.SmallIntegerField(blank=0, choices=[(1, 'CURE_POISON'), (2, 'STRENGTH'), (3, 'SPEED'), (4, 'INVISIBLE'), (5, 'SEE_INVISIBLE'), (6, 'HEAL'), (7, 'HURT'), (8, 'SLEEP'), (9, 'PUSH'), (10, 'ANNOUNCE'), (11, 'COMMAND'), (12, 'DISTANCE_HURT'), (13, 'DETECT_MAGIC'), (14, 'FIND_PERSON'), (15, 'LOCATE'), (16, 'WEAK'), (17, 'SLOW')], default=0)),
                ('db_affects_room', models.BooleanField(default=False)),
                ('db_affects_caster', models.BooleanField(default=False)),
                ('db_target_prompt', models.BooleanField(default=False)),
                ('db_param_1', models.SmallIntegerField(blank=0, default=0)),
                ('db_param_2', models.SmallIntegerField(blank=0, default=0)),
                ('db_param_3', models.SmallIntegerField(blank=0, default=0)),
                ('db_param_4', models.SmallIntegerField(blank=0, default=0)),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdefined.Spell')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
