# Generated by Django 2.2.10 on 2020-03-14 03:16

from django.db import migrations, models
import django.db.models.deletion
import gamerules.spell_effect_kind


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_record_id', models.PositiveSmallIntegerField(db_index=True)),
                ('db_key', models.CharField(db_index=True, max_length=32, unique=True)),
                ('db_who_name', models.CharField(max_length=16)),
                ('db_group', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_size', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_alignment', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_move_speed', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_attack_speed', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_heal_speed', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_hide_delay', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_base_health', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_level_health', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_base_mana', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_level_mana', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_base_weapon_use', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_level_weapon_use', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_base_claw_damage', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_level_claw_damage', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_random_claw_damage', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_base_steal', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_level_steal', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_base_move_silent', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_level_move_silent', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_armor', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_spell_armor', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_hear_noise', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_poison_chance', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_shadow_damage_percent', models.SmallIntegerField(blank=0, default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_record_id', models.PositiveSmallIntegerField(db_index=True)),
                ('db_key', models.CharField(db_index=True, max_length=32, unique=True)),
                ('db_mana', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_level_mana', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_caster_desc', models.CharField(max_length=256, null=True)),
                ('db_victim_desc', models.CharField(max_length=256, null=True)),
                ('db_alignment', models.SmallIntegerField(blank=0, default=0)),
                ('db_failure_desc', models.CharField(max_length=256, null=True)),
                ('db_min_level', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_class_id', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_group', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_room', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_failure_chance', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_casting_time', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_object_required', models.CharField(max_length=32, null=True)),
                ('db_object_consumed', models.BooleanField(default=False)),
                ('db_silent', models.BooleanField(default=False)),
                ('db_reveals', models.BooleanField(default=False)),
                ('db_memorize', models.BooleanField(default=False)),
                ('db_command', models.CharField(max_length=32, null=True)),
                ('db_command_priv', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpellEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_effect_kind', models.CharField(choices=[(gamerules.spell_effect_kind.SpellEffectKind(1), 1), (gamerules.spell_effect_kind.SpellEffectKind(2), 2), (gamerules.spell_effect_kind.SpellEffectKind(3), 3), (gamerules.spell_effect_kind.SpellEffectKind(4), 4), (gamerules.spell_effect_kind.SpellEffectKind(5), 5), (gamerules.spell_effect_kind.SpellEffectKind(6), 6), (gamerules.spell_effect_kind.SpellEffectKind(7), 7), (gamerules.spell_effect_kind.SpellEffectKind(8), 8), (gamerules.spell_effect_kind.SpellEffectKind(9), 9), (gamerules.spell_effect_kind.SpellEffectKind(10), 10), (gamerules.spell_effect_kind.SpellEffectKind(11), 11), (gamerules.spell_effect_kind.SpellEffectKind(12), 12), (gamerules.spell_effect_kind.SpellEffectKind(13), 13), (gamerules.spell_effect_kind.SpellEffectKind(14), 14), (gamerules.spell_effect_kind.SpellEffectKind(15), 15), (gamerules.spell_effect_kind.SpellEffectKind(16), 16), (gamerules.spell_effect_kind.SpellEffectKind(17), 17)], max_length=16)),
                ('db_affects_room', models.BooleanField(default=False)),
                ('db_affects_caster', models.BooleanField(default=False)),
                ('db_target_prompt', models.BooleanField(default=False)),
                ('db_param_1', models.SmallIntegerField(blank=0, default=0)),
                ('db_param_2', models.SmallIntegerField(blank=0, default=0)),
                ('db_param_3', models.SmallIntegerField(blank=0, default=0)),
                ('db_param_4', models.SmallIntegerField(blank=0, default=0)),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdefined.Spell')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
