# Generated by Django 2.2.10 on 2020-03-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_record_id', models.PositiveSmallIntegerField(db_index=True)),
                ('db_key', models.CharField(db_index=True, max_length=32, unique=True)),
                ('db_who_name', models.CharField(max_length=16)),
                ('db_group', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_size', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_alignment', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_move_speed', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_attack_speed', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_heal_speed', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_hide_delay', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_base_health', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_level_health', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_base_mana', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_level_mana', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_base_weapon_use', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_level_weapon_use', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_base_claw_damage', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_level_claw_damage', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_random_claw_damage', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_base_steal', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_level_steal', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_base_move_silent', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_level_move_silent', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_armor', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_spell_armor', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_hear_noise', models.PositiveSmallIntegerField(blank=0, default=0)),
                ('db_poison_chance', models.PositiveSmallIntegerField(blank=0, default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
