from enum import IntEnum


class SpecialRoomKind(IntEnum):
  MARKET = 0
  NO_COMBAT = 1
  NO_HIDE = 2
  HARD_TO_HIDE = 3
  OBJECT_DESTROY = 4
  TREASURE_DROP = 5
  MONSTER_GENERATOR = 6
  MONSTER_GENERATOR_GROUP = 7
  MONSTER_LAIR = 8
  MONSTER_GENERATOR_MIN_LEVEL = 9
  MONSTER_GENERATOR_MAX_LEVEL = 10
  HEAL = 11