#
# Generated mob prototypes
#
from gamerules.mob_kind import MobKind


MOB = {
  'typeclass': 'typeclasses.mobs.Mob',
  'key': 'mob',
}


BUGBEAR = {
  'key': "Bugbear",
  'prototype_parent': 'mob',
  'record_id': 1,
  'prototype_tags': ['mob', 'min_level_4', 'record_id_1'],
  'kind': MobKind.FIGHTER,
  'min_level': 4,
  'group': 0,
  'size': 7,
  'xp': 1600,
  'drop_gold': 10,
  'drop_object_id': 0,
  'base_health': 1400,
  'random_health': 300,
  'level_health': 0,
  'base_mana': 0,
  'level_mana': 0,
  'base_damage': 45,
  'random_damage': 110,
  'level_damage': 35,
  'armor': 10,
  'spell_armor': 0,
  'move_speed': 40,
  'attack_speed': 150,
  'heal_speed': 250,
  'attack_name': 'iron bar',
  'weapon_use': 0,
  'level_weapon_use': 0,
  'pursuit_chance': 25,
}

EVIL_DWARF = {
  'key': "Evil Dwarf",
  'prototype_parent': 'mob',
  'record_id': 2,
  'prototype_tags': ['mob', 'min_level_4', 'record_id_2'],
  'kind': MobKind.FIGHTER,
  'min_level': 4,
  'group': 5,
  'size': 4,
  'xp': 2001,
  'drop_gold': 6,
  'drop_object_id': 0,
  'base_health': 1000,
  'random_health': 1000,
  'level_health': 0,
  'base_mana': 0,
  'level_mana': 0,
  'base_damage': 99,
  'random_damage': 50,
  'level_damage': 12,
  'armor': 12,
  'spell_armor': 0,
  'move_speed': 55,
  'attack_speed': 150,
  'heal_speed': 250,
  'attack_name': 'axe',
  'weapon_use': 100,
  'level_weapon_use': 5,
  'pursuit_chance': 35,
}

WHITE_DRAGON = {
  'key': "White Dragon",
  'prototype_parent': 'mob',
  'record_id': 3,
  'prototype_tags': ['mob', 'min_level_7', 'record_id_3'],
  'kind': MobKind.FIGHTER,
  'min_level': 7,
  'group': 0,
  'size': 20,
  'xp': 3000,
  'drop_gold': 80,
  'drop_object_id': 0,
  'base_health': 3500,
  'random_health': 2000,
  'level_health': 0,
  'base_mana': 0,
  'level_mana': 0,
  'base_damage': 205,
  'random_damage': 115,
  'level_damage': 35,
  'armor': 20,
  'spell_armor': 0,
  'move_speed': 25,
  'attack_speed': 120,
  'heal_speed': 400,
  'weapon_use': 140,
  'level_weapon_use': 10,
  'pursuit_chance': 35,
}

RED_DRAGON = {
  'key': "Red Dragon",
  'prototype_parent': 'mob',
  'record_id': 4,
  'prototype_tags': ['mob', 'min_level_7', 'record_id_4'],
  'kind': MobKind.FIGHTER,
  'min_level': 7,
  'group': 0,
  'size': 0,
  'xp': 4100,
  'drop_gold': 89,
  'drop_object_id': 0,
  'base_health': 3500,
  'random_health': 3000,
  'level_health': 0,
  'base_mana': 0,
  'level_mana': 0,
  'base_damage': 275,
  'random_damage': 145,
  'level_damage': 45,
  'armor': 20,
  'spell_armor': 0,
  'move_speed': 65,
  'attack_speed': 140,
  'heal_speed': 500,
  'weapon_use': 100,
  'level_weapon_use': 5,
  'pursuit_chance': 15,
}

GHOST = {
  'key': "Ghost",
  'prototype_parent': 'mob',
  'record_id': 5,
  'prototype_tags': ['mob', 'min_level_5', 'record_id_5'],
  'kind': MobKind.FIGHTER,
  'min_level': 5,
  'group': 0,
  'size': 6,
  'xp': 750,
  'drop_gold': 80,
  'drop_object_id': 0,
  'base_health': 2800,
  'random_health': 300,
  'level_health': 0,
  'base_mana': 0,
  'level_mana': 0,
  'base_damage': 100,
  'random_damage': 50,
  'level_damage': 30,
  'armor': 3,
  'spell_armor': 50,
  'move_speed': 80,
  'attack_speed': 130,
  'heal_speed': 100,
  'weapon_use': 0,
  'level_weapon_use': 0,
  'pursuit_chance': 100,
}

PILGRIM = {
  'key': "Pilgrim",
  'prototype_parent': 'mob',
  'record_id': 6,
  'prototype_tags': ['mob', 'min_level_0', 'record_id_6'],
  'kind': MobKind.FIGHTER,
  'min_level': 0,
  'group': 0,
  'size': 6,
  'xp': 0,
  'drop_gold': 9,
  'drop_object_id': 0,
  'base_health': 350,
  'random_health': 200,
  'level_health': 0,
  'base_mana': 0,
  'level_mana': 0,
  'base_damage': 10,
  'random_damage': 0,
  'level_damage': 0,
  'armor': 0,
  'spell_armor': 0,
  'move_speed': 100,
  'attack_speed': 450,
  'heal_speed': 250,
  'weapon_use': 0,
  'level_weapon_use': 0,
  'pursuit_chance': 60,
}

DRUNKEN_WARRIOR = {
  'key': "Drunken Warrior",
  'prototype_parent': 'mob',
  'record_id': 7,
  'prototype_tags': ['mob', 'min_level_3', 'record_id_7'],
  'kind': MobKind.FIGHTER,
  'min_level': 3,
  'group': 0,
  'size': 0,
  'xp': 900,
  'drop_gold': 6,
  'drop_object_id': 0,
  'base_health': 400,
  'random_health': 200,
  'level_health': 0,
  'base_mana': 0,
  'level_mana': 0,
  'base_damage': 0,
  'random_damage': 250,
  'level_damage': 0,
  'armor': 0,
  'spell_armor': 0,
  'move_speed': 60,
  'attack_speed': 500,
  'heal_speed': 250,
  'attack_name': 'longsword',
  'weapon_use': 0,
  'level_weapon_use': 0,
  'pursuit_chance': 25,
}

LORD_GRAZZTS_GHOST = {
  'key': "Lord Grazz't's Ghost",
  'prototype_parent': 'mob',
  'record_id': 8,
  'prototype_tags': ['mob', 'min_level_5', 'record_id_8'],
  'kind': MobKind.FIGHTER,
  'min_level': 5,
  'group': 0,
  'size': 6,
  'xp': 2000,
  'drop_gold': 0,
  'drop_object_id': 0,
  'base_health': 500,
  'random_health': 500,
  'level_health': 0,
  'base_mana': 0,
  'level_mana': 0,
  'base_damage': 100,
  'random_damage': 175,
  'level_damage': 0,
  'armor': 15,
  'spell_armor': 15,
  'move_speed': 40,
  'attack_speed': 110,
  'heal_speed': 250,
  'weapon_use': 100,
  'level_weapon_use': 0,
  'pursuit_chance': 25,
}

CRUSADERS_SHADE = {
  'key': "Crusader's Shade",
  'prototype_parent': 'mob',
  'record_id': 9,
  'prototype_tags': ['mob', 'min_level_4', 'record_id_9'],
  'kind': MobKind.FIGHTER,
  'min_level': 4,
  'group': 0,
  'size': 6,
  'xp': 2500,
  'drop_gold': 0,
  'drop_object_id': 0,
  'base_health': 500,
  'random_health': 400,
  'level_health': 0,
  'base_mana': 0,
  'level_mana': 0,
  'base_damage': 125,
  'random_damage': 125,
  'level_damage': 0,
  'armor': 10,
  'spell_armor': 10,
  'move_speed': 50,
  'attack_speed': 110,
  'heal_speed': 250,
  'weapon_use': 0,
  'level_weapon_use': 0,
  'pursuit_chance': 25,
}

FROST_GIANT = {
  'key': "Frost Giant",
  'prototype_parent': 'mob',
  'record_id': 10,
  'prototype_tags': ['mob', 'min_level_6', 'record_id_10'],
  'kind': MobKind.FIGHTER,
  'min_level': 6,
  'group': 0,
  'size': 12,
  'xp': 2010,
  'drop_gold': 25,
  'drop_object_id': 0,
  'base_health': 2500,
  'random_health': 500,
  'level_health': 0,
  'base_mana': 0,
  'level_mana': 0,
  'base_damage': 180,
  'random_damage': 100,
  'level_damage': 0,
  'armor': 15,
  'spell_armor': 0,
  'move_speed': 60,
  'attack_speed': 180,
  'heal_speed': 250,
  'weapon_use': 0,
  'level_weapon_use': 0,
  'pursuit_chance': 65,
}

FIRE_GIANT = {
  'key': "Fire Giant",
  'prototype_parent': 'mob',
  'record_id': 11,
  'prototype_tags': ['mob', 'min_level_5', 'record_id_11'],
  'kind': MobKind.FIGHTER,
  'min_level': 5,
  'group': 12,
  'size': 10,
  'xp': 2000,
  'drop_gold': 20,
  'drop_object_id': 0,
  'base_health': 1600,
  'random_health': 600,
  'level_health': 0,
  'base_mana': 0,
  'level_mana': 0,
  'base_damage': 200,
  'random_damage': 50,
  'level_damage': 0,
  'armor': 15,
  'spell_armor': 0,
  'move_speed': 60,
  'attack_speed': 150,
  'heal_speed': 250,
  'weapon_use': 0,
  'level_weapon_use': 0,
  'pursuit_chance': 65,
}

TOAD_MAN = {
  'key': "Toad Man",
  'prototype_parent': 'mob',
  'record_id': 12,
  'prototype_tags': ['mob', 'min_level_0', 'record_id_12'],
  'kind': MobKind.FIGHTER,
  'min_level': 0,
  'group': 0,
  'size': 4,
  'xp': 0,
  'drop_gold': 2,
  'drop_object_id': 0,
  'base_health': 550,
  'random_health': 150,
  'level_health': 524409,
  'base_mana': 0,
  'level_mana': 0,
  'base_damage': 105,
  'random_damage': 0,
  'level_damage': 0,
  'armor': 0,
  'spell_armor': 0,
  'move_speed': 45,
  'attack_speed': 150,
  'heal_speed': 250,
  'weapon_use': 0,
  'level_weapon_use': 0,
  'pursuit_chance': 35,
}

KOBOLD = {
  'key': "Kobold",
  'prototype_parent': 'mob',
  'record_id': 13,
  'prototype_tags': ['mob', 'min_level_0', 'record_id_13'],
  'kind': MobKind.FIGHTER,
  'min_level': 0,
  'group': 0,
  'size': 4,
  'xp': 600,
  'drop_gold': 1,
  'drop_object_id': 0,
  'base_health': 825,
  'random_health': 225,
  'level_health': 524409,
  'base_mana': 0,
  'level_mana': 0,
  'base_damage': 135,
  'random_damage': 0,
  'level_damage': 0,
  'armor': 0,
  'spell_armor': 0,
  'move_speed': 45,
  'attack_speed': 150,
  'heal_speed': 250,
  'weapon_use': 0,
  'level_weapon_use': 0,
  'pursuit_chance': 25,
}

PUGNACIOUS_RUNT = {
  'key': "Pugnacious Runt",
  'prototype_parent': 'mob',
  'record_id': 14,
  'prototype_tags': ['mob', 'min_level_0', 'record_id_14'],
  'kind': MobKind.FIGHTER,
  'min_level': 0,
  'group': 0,
  'size': 4,
  'xp': 0,
  'drop_gold': 1,
  'drop_object_id': 0,
  'base_health': 350,
  'random_health': 100,
  'level_health': 0,
  'base_mana': 0,
  'level_mana': 0,
  'base_damage': 50,
  'random_damage': 50,
  'level_damage': 0,
  'armor': 0,
  'spell_armor': 0,
  'move_speed': 50,
  'attack_speed': 150,
  'heal_speed': 250,
  'weapon_use': 100,
  'level_weapon_use': 0,
  'pursuit_chance': 0,
}

SOLDIER = {
  'key': "Soldier",
  'prototype_parent': 'mob',
  'record_id': 15,
  'prototype_tags': ['mob', 'min_level_10', 'record_id_15'],
  'kind': MobKind.FIGHTER,
  'min_level': 10,
  'group': 0,
  'size': 6,
  'xp': 1500,
  'drop_gold': 20,
  'drop_object_id': 0,
  'base_health': 1000,
  'random_health': 100,
  'level_health': 1684956448,
  'base_mana': 0,
  'level_mana': 0,
  'base_damage': 80,
  'random_damage': 150,
  'level_damage': 10,
  'armor': 8,
  'spell_armor': 2,
  'move_speed': 50,
  'attack_speed': 100,
  'heal_speed': 0,
  'weapon_use': 0,
  'level_weapon_use': 0,
  'pursuit_chance': 0,
}

VAMPIRE = {
  'key': "Vampire",
  'prototype_parent': 'mob',
  'record_id': 16,
  'prototype_tags': ['mob', 'min_level_6', 'record_id_16'],
  'kind': MobKind.FIGHTER,
  'min_level': 6,
  'group': 0,
  'size': 0,
  'xp': 3000,
  'drop_gold': 66,
  'drop_object_id': 0,
  'base_health': 1400,
  'random_health': 400,
  'level_health': 1768776814,
  'base_mana': 0,
  'level_mana': 0,
  'base_damage': 150,
  'random_damage': 100,
  'level_damage': 20,
  'armor': 15,
  'spell_armor': 14,
  'move_speed': 0,
  'attack_speed': 160,
  'heal_speed': 100,
  'weapon_use': 100,
  'level_weapon_use': 10,
  'pursuit_chance': 0,
}

DANCING_SWORD = {
  'key': "Dancing Sword",
  'prototype_parent': 'mob',
  'record_id': 17,
  'prototype_tags': ['mob', 'min_level_0', 'record_id_17'],
  'kind': MobKind.FIGHTER,
  'min_level': 0,
  'group': 0,
  'size': 0,
  'xp': 0,
  'drop_gold': 0,
  'drop_object_id': 0,
  'base_health': 500,
  'random_health': 400,
  'level_health': 0,
  'base_mana': 0,
  'level_mana': 0,
  'base_damage': 30,
  'random_damage': 100,
  'level_damage': 0,
  'armor': 0,
  'spell_armor': 0,
  'move_speed': 0,
  'attack_speed': 150,
  'heal_speed': 0,
  'weapon_use': 0,
  'level_weapon_use': 0,
  'pursuit_chance': 0,
}

GREEN_SLIME = {
  'key': "Green Slime",
  'prototype_parent': 'mob',
  'record_id': 18,
  'prototype_tags': ['mob', 'min_level_4', 'record_id_18'],
  'kind': MobKind.FIGHTER,
  'min_level': 4,
  'group': 0,
  'size': 10,
  'xp': 2100,
  'drop_gold': 30,
  'drop_object_id': 0,
  'base_health': 1500,
  'random_health': 0,
  'level_health': 0,
  'base_mana': 0,
  'level_mana': 0,
  'base_damage': 100,
  'random_damage': 120,
  'level_damage': 0,
  'armor': 30,
  'spell_armor': 0,
  'move_speed': 0,
  'attack_speed': 140,
  'heal_speed': 0,
  'weapon_use': 90,
  'level_weapon_use': 0,
  'pursuit_chance': 0,
}

CTHULHU = {
  'key': "Cthulhu",
  'prototype_parent': 'mob',
  'record_id': 19,
  'prototype_tags': ['mob', 'min_level_10', 'record_id_19'],
  'kind': MobKind.FIGHTER,
  'min_level': 10,
  'group': 0,
  'size': 10,
  'xp': 99999999,
  'drop_gold': 9999999,
  'drop_object_id': 0,
  'base_health': 9999999,
  'random_health': 99999,
  'level_health': 0,
  'base_mana': 0,
  'level_mana': 0,
  'base_damage': 9999999,
  'random_damage': 999999,
  'level_damage': 99999,
  'armor': 50,
  'spell_armor': 50,
  'move_speed': 2,
  'attack_speed': 0,
  'heal_speed': 250,
  'weapon_use': 0,
  'level_weapon_use': 0,
  'pursuit_chance': 0,
}

