from enum import IntEnum

# from equip.inc ef_* constants
class EquipmentEffectKind(IntEnum):
  GROUP = 1
  CLASS = 2
  BASE_HEALTH = 3
  LEVEL_HEALTH = 4
  BASE_MANA = 5
  LEVEL_MANA = 6
  BASE_STEAL = 7
  LEVEL_STEAL = 8
  BASE_MOVE_SILENT = 9
  LEVEL_MOVE_SILENT = 10
  MOVE_SPEED = 11
  HEAL_SPEED = 12
  ATTACK_SPEED = 13
  BASE_CLAW_DAMAGE = 14
  RANDOM_CLAW_DAMAGE = 15
  LEVEL_CLAW_DAMAGE = 16
  CAST_SPELL = 17
  XP = 18
  BASE_WEAPON_USE = 19
  SIZE = 20
  HEAR_NOISE = 21
  LEVEL_WEAPON_USE = 22
  POISON = 23
  CONTROL = 24
  INVISIBLE = 25
  SEE_INVISIBLE = 26
  BASE_WEAPON_DAMAGE = 27
  RANDOM_WEAPON_DAMAGE = 28
  BASE_ARMOR = 29
  DEFLECT_ARMOR = 30
  SPELL_ARMOR = 31
  SMALLEST_FIT = 32
  LARGEST_FIT = 33
  CONDITION = 34
  BREAK_CHANCE = 35
  BREAK_MAGNITUDE = 36
  CHARGES = 37
  SPELL = 38
  # spell deflect aka spell destroy
  SPELL_DEFLECT_ARMOR = 39
  THROW_BASE = 40
  THROW_RANDOM = 41
  THROW_RANGE = 42
  THROW_BEHAVIOR = 43
  CURSED = 44
  # 45,46 missing?
  NO_THROW = 47
  BOMB_BASE = 48
  BOMB_RANDOM = 49
  BOMB_TIME = 50
  # 51 missing?
  TRAP = 52
  DROP_DESTROY = 57
  CRYSTAL_RADIUS = 58
  TELEPORT = 59



